"""MCP client: connects to MCP servers and wraps their tools as native nanobot tools."""

import asyncio
from contextlib import AsyncExitStack
from typing import Any

import httpx
from loguru import logger

from nanobot.agent.tools.base import Tool
from nanobot.agent.tools.registry import ToolRegistry


class MCPToolWrapper(Tool):
    """Wraps a single MCP server tool as a nanobot Tool."""

    def __init__(self, session, server_name: str, tool_def, cfg, tool_timeout: int = 30):
        self._session = session
        self._original_name = tool_def.name
        self._name = f"mcp_{server_name}_{tool_def.name}"
        self._description = tool_def.description or tool_def.name
        self._tool_timeout = tool_timeout
        
        # Parameter injection: match cfg attributes with tool parameters
        params = tool_def.inputSchema or {"type": "object", "properties": {}}
        if "properties" in params:
            # Extract potential defaults from cfg (including Pydantic V2 model_extra)
            defaults = {}
            known = {"command", "args", "env", "url", "headers", "tool_timeout"}
            
            # 1. From defined fields
            for k, v in cfg.__dict__.items():
                if k not in known and not k.startswith("_") and isinstance(v, str):
                    defaults[k.lower()] = v
            
            # 2. From extra fields (Pydantic V2)
            if hasattr(cfg, "model_extra") and cfg.model_extra:
                for k, v in cfg.model_extra.items():
                    if isinstance(v, str):
                        defaults[k.lower()] = v
            
            # Inject defaults and update descriptions to guide LLM
            for p_name, p_schema in params["properties"].items():
                if p_name.lower() in defaults:
                    p_schema["default"] = defaults[p_name.lower()]
                    # Explicitly tell LLM NOT to fill this manually
                    orig_desc = p_schema.get("description", "")
                    p_schema["description"] = f"{orig_desc} (ALREADY PRE-CONFIGURED BY SYSTEM, DO NOT CHANGE)".strip()
                    logger.debug("MCP Tool '{}': injected default and hint for '{}'", self._name, p_name)
        
        self._parameters = params
        self._cfg = cfg

    @property
    def name(self) -> str:
        return self._name

    @property
    def description(self) -> str:
        return self._description

    @property
    def parameters(self) -> dict[str, Any]:
        return self._parameters

    async def execute(self, **kwargs: Any) -> str:
        from mcp import types
        # Parameter enforcement logic (Scheme U)
        if "properties" in self._parameters:
            for p_name, p_schema in self._parameters["properties"].items():
                # 1. Fill missing arguments
                if p_name not in kwargs and "default" in p_schema:
                    kwargs[p_name] = p_schema["default"]
                # 2. Hard replace dummy values generated by LLM hallucinations
                elif p_name in kwargs and "default" in p_schema:
                    val = str(kwargs[p_name]).strip().lower()
                    if val in ("dummy_token", "default", "your_token", "api_key_here", "null"):
                        kwargs[p_name] = p_schema["default"]
                        kwargs[p_name] = p_schema["default"]
                        logger.warning("MCP: Hard-replaced dummy value for '{}' with config default", p_name)

        logger.info("Executing MCP tool '{}' with args: {}", self._name, kwargs)
        try:
            result = await asyncio.wait_for(
                self._session.call_tool(self._original_name, arguments=kwargs),
                timeout=self._tool_timeout,
            )
        except asyncio.TimeoutError:
            logger.warning("MCP tool '{}' timed out after {}s", self._name, self._tool_timeout)
            return f"(MCP tool call timed out after {self._tool_timeout}s)"
        parts = []
        for block in result.content:
            if isinstance(block, types.TextContent):
                parts.append(block.text)
            else:
                parts.append(str(block))
        return "\n".join(parts) or "(no output)"


async def connect_mcp_servers(
    mcp_servers: dict, registry: ToolRegistry, stack: AsyncExitStack
) -> None:
    """Connect to configured MCP servers and register their tools."""
    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client
    from mcp.client.sse import sse_client

    for name, cfg in mcp_servers.items():
        try:
            if cfg.command:
                params = StdioServerParameters(
                    command=cfg.command, args=cfg.args, env=cfg.env or None
                )
                read, write = await stack.enter_async_context(stdio_client(params))
            elif cfg.url:
                # Extract any extra fields from cfg as headers (e.g. Authorization, Modeltype)
                combined_headers = dict(cfg.headers or {})
                known = {"command", "args", "env", "url", "headers", "tool_timeout"}
                for k, v in cfg.__dict__.items():
                    if k not in known and not k.startswith("_") and isinstance(v, str):
                        combined_headers[k] = v
                
                # Check model_extra for Pydantic V2
                if hasattr(cfg, "model_extra") and cfg.model_extra:
                    for k, v in cfg.model_extra.items():
                        if isinstance(v, str):
                            combined_headers[k] = v

                if "/sse" in cfg.url or "iheatingos.com" in cfg.url:
                    # Use specialized SSE client for SSE endpoints
                    # Pass a very large read timeout to prevent the default 5-minute disconnect of httpx
                    read, write = await stack.enter_async_context(
                        sse_client(cfg.url, headers=combined_headers, sse_read_timeout=60 * 60 * 24 * 7)
                    )
                else:
                    from mcp.client.streamable_http import streamable_http_client
                    # Always provide an explicit httpx client so MCP HTTP transport does not
                    # inherit httpx's default 5s timeout and preempt the higher-level tool timeout.
                    http_client = await stack.enter_async_context(
                        httpx.AsyncClient(
                            headers=combined_headers if combined_headers else None,
                            follow_redirects=True,
                            timeout=httpx.Timeout(None, connect=5.0),
                        )
                    )
                    read, write, _ = await stack.enter_async_context(
                        streamable_http_client(cfg.url, http_client=http_client)
                    )
            else:
                logger.warning("MCP server '{}': no command or url configured, skipping", name)
                continue

            session = await stack.enter_async_context(ClientSession(read, write))
            await session.initialize()

            tools = await session.list_tools()
            for tool_def in tools.tools:
                wrapper = MCPToolWrapper(session, name, tool_def, cfg, tool_timeout=cfg.tool_timeout)
                registry.register(wrapper)
                logger.debug("MCP: registered tool '{}' from server '{}'", wrapper.name, name)

            logger.info("MCP server '{}': connected, {} tools registered", name, len(tools.tools))
        except Exception as e:
            logger.error("MCP server '{}': failed to connect: {}", name, e)
